Added the pet addition, added terms and condition popup, changed the docker compose file for deployment

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -14,7 +14,7 @@ COPY . .
 
 CMD ["pnpm", "run", "dev"]
 
-FROM node:18-alpine as production
+FROM node:18-alpine AS production
 
 ENV PNPM_HOME="/pnpm"
 ENV PATH="$PNPM_HOME:$PATH"
@@ -22,9 +22,14 @@ RUN corepack enable && corepack prepare pnpm@latest --activate
 
 WORKDIR /app
 
-COPY . .
+COPY package*.json pnpm-lock.yaml ./
 
 RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
-RUN pnpm run build && echo "Build ran"
+
+COPY . .
+
+RUN pnpm run build && echo "✅ Build ran" && ls -la && ls -R .next || (echo "❌ Build failed" && exit 1)
+
+EXPOSE 3000
 
 CMD [ "pnpm", "start" ]
